import { faGlobeEurope } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <span>Hello World!</span>
      {[...Array(1000).keys()].map((n, ind) => <FontAwesomeIcon key={ind} icon={faGlobeEurope} />)}
    </div>
  )
}
